<main class="player">
    <div class="portrait">
        <h2></h2>
        <img src="" alt="">
    </div>
    <div class="perfs">
        <h2>Ses performances</h2>
        <table>
            <th>
                <td>Team adverse</td>
                <td>Points</td>
                <td>Assists</td>
                <td>Victoire ?</td>
            </th>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="sa-team">
        <div class="card-player">
            <img src="" alt="">
            <h5></h5>
            <a href=""><button type="button">Découvrez</button></a>
        </div>
    </div>
</main>