<section class="games">
    <h2>Les matchs</h2>
    <div class="games-grid">
        <?php foreach($data["games"] as $game) { ?>
        <div class="game-card">
            <h4><?= $game->getName() ?></h4>
            <p><?=$game->getDate()?></p>
                <?php foreach($data["teams"] as $team) { ?>
                    <?php if($team -> getName() === $game -> getWinner()) { ?>
                        <img src="<?= $team ->getLogo()?>" alt ="logo de <?= $team -> getName() ?>" class="winner">
                    <?php } else if($team -> getName() === $game -> getTeam_1() || $team -> getName() === $game -> getTeam_2()) { ?>
                        <img src="<?= $team ->getLogo()?>" alt ="logo de <?= $team -> getName() ?>">
                    <?php } ?>
                <?php } ?>
            <div class="button-div">
                <a href="#"><button type="button">Détails du match</button></a>
            </div>
        </div>
        <?php } ?>
    </div>
</section>