<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>The League</title>
        <link rel="stylesheet" href="assets/style.css" />
    </head>
    <body>
        <header class="header">
            <a href="index.php"><h1>THE LEAGUE</h1></a>
            <nav>
                <ul>
                    <a href="index.php?route=teams">
                        <li>Les teams</li>
                    </a>
                    <a href="index.php?route=players">
                        <li>Les players</li>
                    </a>
                    <a href="index.php?route=games">
                        <li>Les matchs</li>
                    </a>
                </ul>
            </nav>
        </header>
        <?php
            require "templates/$template.phtml"
        ?>
    </body>
</html>