<main class="players">
    <h2>Les players de la league</h2>
    <div class="grid-players">
        <?php foreach($data as $player) { ?>
            <div class="card-player">
                <img src="<?= $player -> getPortrait() ?>" alt="Logo de <?= $player -> getNickname() ?>">
                <h5><?= $player -> getNickname() ?></h5>
                <p><?= $player -> getTeam() ?></p>
                <a href="index.php?route=playerDetails&player_id=<?= $player -> getId() ?>"><button type="button">Découvrez <?= $player -> getNickname() ?></button></a>
            </div>
        <?php } ?>
</main>